name: 'Verify Terraform'
on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ''

jobs:
  verify-terraform:
    name: 'Verify Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Validate Terraform'
        run: |
          echo "TODO"
