name: 'Build and Test'
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: ubuntu-latest
    secrets:
      SONAR_TOKEN:

jobs:
  build:
    name: 'Build and Test'
    runs-on: ${{ inputs.runner }}
    steps:
      - name: 'Setup Maven'
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          java-distribution: 'liberica'
          #settings-repositories: '...'

      - name: 'Build and test'
        run: |
          mvn -e -B -no-transfer-progress clean jacoco:prepare-agent verify jacoco:report

      - name: 'Publish test results'
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: 'Test Results'
          path: '**/target/surefire-reports/**/*.xml'
          reporter: java-junit

      - name: 'SonarCloud'
        if: github.actor != 'dependabot[bot]'
        run: |
          mvn -e -B -no-transfer-progress sonar:sonar
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
          SONAR_HOST_URL: "https://sonarcloud.io"

      - name: SonarCloud Quality Gate check
        if: github.actor != 'dependabot[bot]'
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: target/sonar/report-task.txt
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
          SONAR_HOST_URL: "https://sonarcloud.io"
