name: Build
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      service-folder:
        type: string
        default: '.'

jobs:
  build:
    name: 'Build'
    uses: hwolf/workflows/.github/workflows/build.yml@main
    with:
      publish-image: ${{ inputs.environment != 'none' }}
    secrets: inherit

  terraform:
    name: 'Validate Terraform'
    uses: hwolf/workflows/.github/workflows/verify-terraform.yml@main

  deploy:
    name: 'Deploy'
    if: inputs.environment != 'none'
    needs:
      - build
      - terraform
    uses: hwolf/workflows/.github/workflows/deploy.yml@main
    with:
      revision: "${{ needs.build.outputs.revision }}"
      environment: "${{ inputs.environment }}"
