name: 'Build and Test'
on:
  workflow_call:
    inputs:
      publish-image:
        type: boolean
        default: false
      service-folder:
        type: string
        default: '.'
    secrets:
      SONAR_TOKEN:
    outputs:
      revision:
        value: ${{ jobs.build.outputs.revision }}

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    outputs:
      revision: ${{ steps.revision.outputs.revision }}
    steps:
      - name: 'Calculate revision (main)'
        if: github.ref == 'refs/heads/main'
        run: |
          echo "revision=$(date +%Y%m%d)-${{ github.run_number }}" >> $GITHUB_ENV
      - name: 'Calculate revision (branch)'
        if: github.ref != 'refs/heads/main'
        run: |
          echo "revision=$(date +%Y%m%d)-${{ github.sha }}-${{ github.run_number }}" >> $GITHUB_ENV
      - name: 'Setup Maven'
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          java-distribution: 'liberica'
          #settings-repositories: '...'
          #checkout-ref: ${{ steps.pr-id.outputs.head_ref }}

      - name: 'Build & Test'
        run: |
          mvn -e -B -no-transfer-progress clean jacoco:prepare-agent package jacoco:report -Drevision="$revision"

      - name: 'Analyse with SonarCloud'
        if: github.actor != 'dependabot[bot]'
        run: |
          mvn -e -B -no-transfer-progress help:system sonar:sonar -Drevision="$revision" -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
          SONAR_HOST_URL: "https://sonarcloud.io"

      - name: 'Build Image'
        working-directory: ${{ inputs.service-folder }}
        run: |
          groupId="$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)"
          artifactId="$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)"
          imageName="xxxx.azurecr.io/${groupId/.//}/$artifactId:$revision"
          echo "imageName=$imageName" >> $GITHUB_ENV

          mvn -e -B -no-transfer-progress spring-boot:build-image-no-fork -Drevision="$revision" \
              -Ddocker.imageName="$imageName"

      - name: 'Login ...'
        if: inputs.publish-image
        run: |
          echo "Login ..."

      - name: 'Publish Image'
        if: inputs.publish-image
        run: |
          echo "Publish image $imageName"

      - name: 'Publish Test Results'
        if: failure()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/target/surefire-reports/**/*.xml'

      #- name: 'Update Dependency Graph'
      #  uses: advanced-security/maven-dependency-submission-action@v4

      - name: Revision
        id: revision
        run: |
          echo "revision=$revision" >> $GITHUB_OUTPUT
