name: Build
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Deploy to environment?
      service-folder:
        type: string
        default: '.'

jobs:
  build:
    name: 'Build'
    uses: hwolf/workflows/.github/workflows/build-and-test.yml@main
    with:
      publish-image: ${{ inputs.environment != 'none' }}
    secrets: inherit

  terraform:
    name: 'Validate Terraform'
    uses: hwolf/workflows/.github/workflows/verify-terraform.yml@main

  deploy:
    name: 'Deploy'
    if: inputs.environment != 'none'
    needs:
      - build
      - terraform
    uses: hwolf/workflows/.github/workflows/deploy.yml@main
    with:
      image-name: "${{ needs.build.outputs.image-name }}"
      environment: "${{ inputs.environment }}"
    secrets: inherit

  create-release-candidate:
    name: 'Create Release Candidate'
    runs-on: ubuntu-latest
    if: inputs.environment == 'qa'
    needs:
      - build
      - deploy
    steps:
      - uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: rc-${{ needs.build.outputs.image-name }}
          release_name: Release ${{ needs.build.outputs.image-name }}
          draft: false
          prerelease: true
