name: Build
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Deploy to environment?
#      revision:
#        type: string
#        required: true
#        description: Revision
      service-folder:
        type: string
        default: '.'

jobs:
  build:
    name: 'Build'
    uses: hwolf/workflows/.github/workflows/build-and-test.yml@main
    with:
#      revision: "${{ inputs.revision }}"
      publish-image: ${{ inputs.environment != 'none' }}
    secrets: inherit

  terraform:
    name: 'Validate Terraform'
    uses: hwolf/workflows/.github/workflows/verify-terraform.yml@main

  deploy:
    name: 'Deploy'
    if: inputs.environment != 'none'
    needs:
      - build
    uses: hwolf/workflows/.github/workflows/deploy.yml@main
    with:
      image-name: "${{ needs.build.outputs.image-name }}"
      environment: "${{ inputs.environment }}"
    secrets: inherit
