name: 'Build and Test'
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: ubuntu-latest
    secrets:
      SONAR_TOKEN:

jobs:
  build:
    name: 'Build and Test'
    runs-on: ${{ inputs.runner }}
    steps:
      - name: 'Setup build'
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          java-distribution: 'liberica'
          checkout-fetch-depth: 0
          #settings-repositories: '...'

      - name: 'Build and test'
        run: |
          mvn -e -B -no-transfer-progress clean jacoco:prepare-agent verify jacoco:report -Drevision=${{ github.ref_name }}

      - name: 'Publish test results'
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: 'Test Results'
          path: '**/target/surefire-reports/**/*.xml'
          reporter: java-junit
          list-suites: failed
          list-tests: failed

      - name: 'SonarCloud'
        if: github.actor != 'dependabot[bot]'
        run: |
          mvn -e -B -no-transfer-progress sonar:sonar -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
          SONAR_HOST_URL: "https://sonarcloud.io"
