name: 'Build and Test'
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: ubuntu-latest
    secrets:
      SONAR_TOKEN:

jobs:
  build:
    name: 'Build and Test'
    runs-on: ${{ inputs.runner }}
    steps:
      - name: 'Setup Maven'
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          java-distribution: 'liberica'
          #settings-repositories: '...'

      - name: 'Build and test'
        run: |
          mvn -e -B -no-transfer-progress clean jacoco:prepare-agent verify jacoco:report

      - name: 'SonarCloud'
        if: github.actor != 'dependabot[bot]'
        run: |
          mvn -e -B -no-transfer-progress sonar:sonar -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
          SONAR_HOST_URL: "https://sonarcloud.io"

      - name: 'Publish test results'
        if: success() || failure()
        uses: r7kamura/report-test-results@v0
        with:
          path: '**/target/surefire-reports/**/*.xml'
