name: 'Deploy'
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      revision:
        type: string
        required: true

concurrency: deploy-${{ inputs.environment }}

jobs:
  deploy:
    name: 'Deploy'
    run-name: 'Deploy image ${{ inputs.revision }} to ${{ inputs.environment }}'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Deploy image'
        run: |
          echo "TODO ..."
          echo "ENV_1=${{ vars.ENV_1 }}"
          echo "SEC_1=${{ secrets.SEC_1 }}"
          echo "SEC_2=${{ secrets.SEC_2 }}"

  tagging:
    name: Tagging
    permissions: write-all
    if: inputs.environment == 'qa' || inputs.environment == 'prd'
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Timestamp
        id: ts
        run: echo "ts=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: 'Create/update tag'
        uses: joutvhu/create-tag@v1
        with:
          tag_name: "${{ inputs.environment }}-deployed-${{ inputs.revision }}"
          message: "Image ${{ inputs.revision }} deployed to ${{ inputs.environment }} at $ts"
          on_tag_exists: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
