name: 'Build and Test'
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
      revision:
        type: string
        required: true

concurrency: ${{ inputs.environment }}

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Deploy ${{ inputs.revision }} to ${{ inputs.environment }}'
        run: |
          echo "TODO ..."
          echo "ENV_1=${{ vars.ENV_1 }}"
          echo "SEC_1=${{ secrets.SEC_1 }}"
          echo "SEC_2=${{ secrets.SEC_2 }}"

      - name: 'Publish SBOM'
        run: |
          echo "TODO ..."

      - name: 'Create tag'
        if: inputs.environment == 'qa' || inputs.environment == 'prd'
        uses: makethenetgo/actions-create-tag@v1
        with:
          tag_name: "${{ inputs.environment }}-deployed-${{ inputs.revision }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
