name: 'Build and Test'
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
      image-name:
        type: string
        required: true

concurrency: ${{ inputs.environment }}

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Deploy ${{ inputs.image-name }} to ${{ inputs.environment }}'
        run: |
          echo "TODO ..."
          echo "ENV_1=${{ vars.ENV_1 }}"
          echo "SEC_1=${{ secrets.SEC_1 }}"
          echo "SEC_2=${{ secrets.SEC_2 }}"

      - name: 'Publish SBOM'
        run: |
          echo "TODO ..."

      - name: Tag
        if: inputs.environment == 'qa' || inputs.environment == 'prd'
        run: |
          imageName=${{ needs.build.outputs.image-name }}
          echo "tag=${imageName#*:}" >> $GITHUB_ENV
      - name: Tag
        if: inputs.environment == 'qa' || inputs.environment == 'prd'
        uses: piszmog/create-tag@v1
        with:
          version: "${{ inputs.environment }}-${{ env.tag }}"
          message: "Deployed ${{ env.tag }} on ${{ inputs.environment }} on $(date '+%Y-%m-%d %H:%M:%S')"
