name: 'Build and Test'
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
      image-name:
        type: string
        required: true
      ref:
        type: string
        default: ''

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ inputs.ref }}

      - run: |
          echo "${{ toJson(github) }}"

      - run: |
          git branch

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Deploy ${{ inputs.image-name }} to ${{ inputs.environment }}'
        run: |
          echo "TODO..."
          echo "${{ toJson(vars) }}"
          echo "$ENV_1"
