name: 'Build and Test'
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      revision:
        type: string
        required: true

concurrency: ${{ inputs.environment }}

jobs:
  deploy:
    name: 'Deploy'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Deploy image ${{ inputs.revision }} to ${{ inputs.environment }}'
        run: |
          echo "TODO ..."
          echo "ENV_1=${{ vars.ENV_1 }}"
          echo "SEC_1=${{ secrets.SEC_1 }}"
          echo "SEC_2=${{ secrets.SEC_2 }}"

      - name: 'Publish SBOM'
        run: |
          echo "TODO ..."

  tagging:
    name: Tagging
    if: inputs.environment == 'qa' || inputs.environment == 'prd'
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: 'Create tag'
        uses: makethenetgo/actions-create-tag@v1
        with:
          tag_name: "${{ inputs.environment }}-deployed-${{ inputs.revision }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sbom:
    name: 'Upload SBOM'
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: 'Setup Maven'
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          java-distribution: 'liberica'

      - name: 'Generate SBOM'
        run: |
          mvn -e -B -no-transfer-progress cyclonedx:makeAggregateBom -Drevision="${{ inputs.revision }}"

      - name: 'Upload SBOM'
        run: |
          find . -name \*.json
          find . -name \*.xml
