name: 'Build and Test'
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
      image-name:
        type: string
        required: true

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Deploy ${{ inputs.image-name }} to ${{ inputs.environment }}'
        run: |
          echo "TODO ..."
          echo "$ENV_1"

      - name: 'Publish SBOM'
        run: |
          echo "TODO ..."
          echo "XX $ENV_1"
