name: 'Deploy'

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      runner:
        type: string
        default: ubuntu-latest

concurrency: deploy-${{ inputs.environment }}

jobs:
  deploy:
    name: 'Deploy'
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runner }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: "${{ github.sha }}"

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Deploy image ${{ github.sha }}'
        run: |
          echo "TODO ..."
          echo "ENV_1=${{ vars.ENV_1 }}"
          echo "SEC_1=${{ secrets.SEC_1 }}"
          echo "SEC_2=${{ secrets.SEC_2 }}"
