name: 'Build and Test'
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: DEV
      image-name:
        type: string
        required: true
      ref:
        type: string
        default: ''

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Deploy ${{ inputs.image-name }} to ${{ inputs.environment }}'
        run: |
          echo "TODO..."
          
