name: 'Deploy'

on:
  workflow_call:
    inputs:
      imageName:
        type: string
      environment:
        type: string
        required: true
      runner:
        type: string
        default: ubuntu-latest

concurrency: deploy-${{ inputs.environment }}

jobs:
  deploy:
    name: 'Deploy'
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runner }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: "${{ github.sha }}"

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Deploy image ${{ inputs.imageName }}:${{ github.sha }}'
        run: |
          docker pull "${{ inputs.imageName }}:${{ github.sha }}"
