name: 'Deploy'

on:
  workflow_call:
    inputs:
      imageName:
        type: string
      environment:
        type: string
        required: true
      runner:
        type: string
        default: ubuntu-latest

concurrency: deploy-${{ inputs.environment }}

jobs:
  deploy:
    name: 'Deploy'
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runner }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: "${{ github.sha }}"

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Deploy image ${{ inputs.imageName }}:${{ github.sha }}'
        run: |
          docker pull "${{ inputs.imageName }}:${{ github.sha }}"

      - name: Tag
        if: inputs.environment == 'prd'
        uses: actions/github-script@v7
        with:
          script: |
            let now = new Date()
            let tag = "prd-" + now.toLocaleString("sv")
                .replaceAll("-", "")
                .replaceAll(":", "")
                .replaceAll(" ", "-")
            let message = "Deployed at " + now.toLocaleString("de", {
              timeZone: "CET",
              timeZoneName: "shortOffset" }) + " to " + "prd"
            let response = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag,
              message: message,
              object: context.sha,
              type: "commit"
            })
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/" + tag,
              sha: response.data.sha
            })
