name: 'Deploy'

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      runner:
        type: string
        default: ubuntu-latest

env:
  imageName: $IMAGE_NAME:${{ github.sha }}

concurrency: deploy-${{ inputs.environment }}

jobs:
  deploy:
    name: 'Deploy'
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runner }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: "${{ github.sha }}"

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Deploy image ${{ env.imageName }}'
        run: |
          echo "TODO ..."
