name: 'Build and publish image'
on:
  workflow_call:
    inputs:
      imageName:
        type: string
      runner:
        type: string
        default: ubuntu-latest

jobs:
  publish:
    name: 'Build and publish image'
    runs-on: ${{ inputs.runner }}
    steps:
      - name: 'Setup build'
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          java-distribution: 'liberica'
          checkout-fetch-depth: 0
          checkout-ref: ${{ github.sha }}
          #settings-repositories: '...'

      - name: 'Build and publish image'
        run: |
          builder=$(grep -e FROM images/builder.Dockerfile | head -n 1)
          echo "B1: $builder"
          builder=${builder/FROM /}
          echo "B2: $builder"
          mvn versions:set-property -Dproperty=image.builder -DnewVersion=$builder

          runImage=$(grep -e FROM images/runImage.Dockerfile | head -n 1)
          echo "R1: $runImage"
          runImage=${runImage/FROM /}
          echo "R2: $runImage"
          mvn versions:set-property -Dproperty=image.runImage -DnewVersion=$runImage

          mvn -e -B -no-transfer-progress spring-boot:build-image -DskipTests \
              -Drevision=${{ github.sha }} \
              -Dimage.builder=$builder \
              -Dimage.runImage=$runImage \
              -Ddocker.publish=true \
              -Ddocker.username=${{ github.actor }} \
              -Ddocker.password=${{ secrets.GITHUB_TOKEN }}
