name: 'Build and publish image'
on:
  workflow_call:
    inputs:
      imageName:
        type: string
      runner:
        type: string
        default: ubuntu-latest

jobs:
  publish:
    name: 'Build and publish image'
    runs-on: ${{ inputs.runner }}
    steps:
      - name: 'Setup build'
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          java-distribution: 'liberica'
          checkout-fetch-depth: 0
          checkout-ref: ${{ github.sha }}
          #settings-repositories: '...'

      - name: 'Build and publish image'
        run: |
          mvn -e -B -no-transfer-progress build-image -DskipTests -Drevision=${{ github.sha }} \
              -Ddocker.publish=true -Ddocker.username=${{ github.actor }} -Ddocker.password=${{ secrets.GITHUB_TOKEN }}

