name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            octokit.rest.git.createTag({
              owner: ${github.owner},
              repo: ${github.repo},
              tag: "Test-1",
              message: "...",
              object: ${github.sha},
              type: 'commit'
            })
