name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          tag_exists_error: false
          message: "Latest release"