name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log("XXX", context);
            console.log("XXX", octokit);
            /*octokit.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "Test-1",
              message: "...",
              object: context.sha,
              type: "commit"
            });*/
