name: Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "Test-1",
              message: "...",
              object: context.sha,
              type: "commit"
            });
